unitDef = {
  unitname               = [[a_bomberdrone]],
  name                   = [[Spicula]],
  description            = [[Fighter Drone]],
  amphibious             = true,
  buildCostEnergy        = 100,
  buildCostMetal         = 100,
  buildPic               = [[fighterdrone.png]],
  buildTime              = 100,
  canAttack              = true,
  canFly                 = true,
  canGuard               = true,
  canMove                = true,
  canPatrol              = true,
  canstop                = [[1]],
  canSubmerge            = false,
  category               = [[FIXEDWING]],
  collide                = false,
  collisionVolumeOffsets = [[0 0 5]],
  collisionVolumeScales  = [[25 8 40]],
  collisionVolumeTest    = 1,
  collisionVolumeType    = [[box]],
  crashDrag              = 0.02,
  cruiseAlt              = 250,
  canLand                = false,

  customParams           = {
    --description_bp = [[Caça básico]],
    description_fr = [[Drone Chasseur]],
    description_de = [[Kappenjaegerdrohne]],
    description_pl = [[Dron mysliwiec]],
    helptext       = [[The Spicula is a fast multirole fighter drone whose particle beam is effective against both land and air targets.]],
    --helptext_bp    = [[Este caça pode atacar unidades aéreas e terrestres e protege bem outras unidades contra unidades aéreas, mas é morto rapidamente por fogo anti-aéreo e caças de superioridade aérea. Funciona melhor contra unidades terrestres quando em grandes números.]],
    --helptext_fr    = [[Capable de tirer en l'air ou au sol le Spicula n'est efficace qu'en groupe. Sa puissance de feu limité le rends moins éfficace qu'un aeronef dédié au combat Air/Sol ou au Air/Air.]],
    helptext_de    = [[Der Spicula ist eine schnelle Kappenjaegerdrohne, der kann Luft- und Landeinheiten schiessen.]],
    helptext_pl    = [[Spicula to szybki wielozadaniowy dron mysliwiec, ktorego bron jest skuteczna przeciwko celom zarowno ladowym, jak i powietrznym.]],
    modelradius    = [[5]],
    refuelturnradius = [[80]],
    is_drone = 1,
  },

  defaultmissiontype     = [[VTOL_standby]],
  explodeAs              = [[GUNSHIPEX]],
  fireState              = 2,
  floater                = true,
  footprintX             = 2,
  footprintZ             = 2,
  frontToSpeed           = 0,
  iconType               = [[scoutplane]],
  idleAutoHeal           = 5,
  idleTime               = 1800,
  maneuverleashlength    = [[400]],
  mass                   = 114,
  maxAcc                 = 0.7,
  maxDamage              = 360,
  maxVelocity            = 8,
  maxElevator            = 0.02,
  maxRudder              = 0.006,
  --maxPitch               = 0.1,
  minCloakDistance       = 75,
  mygravity              = 1,
  noAutoFire             = false,
  noChaseCategory        = [[TERRAFORM SUB]],
  objectName             = [[bomberstrike.s3o]],
  script                 = [[a_bomberdrone.lua]],
  seismicSignature       = 0,
  selfDestructAs         = [[GUNSHIPEX]],

  sfxtypes               = {

    explosiongenerators = {
      [[custom:MUZZLE_ORANGE]],
      [[custom:FF_PUFF]],
      [[custom:BEAMWEAPON_MUZZLE_RED]],
      [[custom:FLAMER]],
    },

  },

  side                   = [[CORE]],
  sightDistance          = 520,
  smoothAnim             = true,
  speedToFront           = 0,
  turnRate               = 9001,
  turnRadius             = 90,

  weapons                = {

    {
      def                = [[MISSILE]],
      badTargetCategory  = [[FIXEDWING]],
      mainDir            = [[0 0 1]],
      maxAngleDif        = 90,      
      onlyTargetCategory = [[FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER SINK SUB]],
    },
  },

  weaponDefs          = {

    MISSILE = {
      name                    = [[Heavy Missiles]],
      areaOfEffect            = 96,
      cegTag                  = [[missiletrailgreen]],
      craterBoost             = 1,
      craterMult              = 2,

      damage                  = {
        default = 450,
        planes  = 450,
      },

      fireStarter             = 70,
      fixedlauncher           = true,
      flightTime              = 3.5,
      impulseBoost            = 0.75,
      impulseFactor           = 0.3,
      interceptedByShieldType = 2,
      model                   = [[wep_m_dragonsfang.s3o]],
      projectiles             = 2,
      range                   = 360,
      reloadtime              = 10,
      smokeTrail              = true,
      soundHit                = [[explosion/ex_med5]],
      soundHitVolume          = 8,
      soundStart              = [[weapon/missile/rapid_rocket_fire2]],
      soundStartVolume        = 7,
      startVelocity           = 190,
      texture2                = [[lightsmoketrail]],
      tracks                  = true,
      trajectoryHeight        = 0.4,
      turnRate                = 24000,
      turret                  = true,
      waterweapon             = true,
      weaponAcceleration      = 90,
      weaponTimer             = 3,
      weaponType              = [[MissileLauncher]],
      weaponVelocity          = 200,
    },
  },
}

return lowerkeys({ a_bomberdrone = unitDef })
